### ISSUE TITLE
Quickpay dotnet client nuget package does not contain assemblies

### ISSUE THREAD

**Issue by imsedim** [QuickPay/quickpay-dotnet-client#2]
Version 1.0.0 (https://www.nuget.org/packages/QuickPay.API.Client/1.0.0) is empty and unusable: there are no DLLs within the package.

Check your https://github.com/QuickPay/quickpay-dotnet-client/blob/master/QuickPay/Quickpay.nuspec file and build configuration.

**Comment by mortenbock** [comment]
+1 (I've notified support about this, but no action so far)
