### ISSUE TITLE
support with .netCore

### ISSUE THREAD

**Issue by radupopConnatix** [QuickPay/quickpay-dotnet-client#4]
DO you know when will be a supported library for .netCore?

**Comment by jepperaskdk** [comment]
Any news on this?

**Comment by ellern** [comment]
Jeg er gået igang med selv at lave lidt, det ligger her: https://github.com/ellern/quickpay-sdk-dotnet samt på nuget: https://www.nuget.org/packages/QuickPay.SDK/

**Comment by Steffen84** [comment]
We have just released a .NET Standard 2.1 version of the SDK
https://www.nuget.org/packages/QuickPay.API.Client
